### PR TITLE
Fix #43 html escaping when layout is false

### LINKED ISSUE #43: caches_action with layout: false produces escaped html output on uncached response
As of actionpack-action_caching 1.2.0, I’m getting escaped HTML for the output of a <code>caches_action</code> action when there is no cache to serve. When the action is already cached, the HTML output is not escaped and pages look/function as expected.

```
class HomeController < ApplicationController

  caches_action :index, layout: false

  …

end
```
Reverting to actionpack-action_caching 1.1.1 restores the expected behavior (html not escaped whether action output is cached or not).

### PR DESCRIPTION
**Pull request by antulik**
Fixes #43. Same as PR #42 but fixes the cause of the problem. 

From [rails docs](http://guides.rubyonrails.org/layouts_and_rendering.html#using-render):
> When using html: option, HTML entities will be escaped if the string is not marked as HTML safe by using html_safe method.

### CODE REVIEW

**Comment by jomo** [comment]
Can confirm this works, tested using
```ruby
gem 'actionpack-action_caching', github: 'antulik/actionpack-action_caching', ref: '8c6e52c69315d67437f480da5dce4b7c8737fb32'
```

**Comment by rafaelcgo** [comment]
Hade the same issue. Hope this gets merged.

**Comment by stephanpavlovic** [comment]
Me too, any reason this doesn't get merged?

**Comment by rafaelfranca** [comment]
It is missing tests.

**Comment by antulik** [comment]
@rafaelfranca updated the tests. Existing tests already test everything, it's just html code doesn't include any html symbols, so fixed that.

**Pull request merged**
